-- Qatar EHS + medication scheduler (apply via: npx prisma db push OR migrate deploy)

-- New enum values and tables are generated by Prisma from schema.prisma.
-- After deploy run: npm run db:seed (from machine with DATABASE_URL)
